services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_USER: postgres  # Specify the username for the "postgres" database
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust